name: GPT Journal Summary

on:
  schedule:
    - cron: '3 23 * * *'  # 05:03 Dubai-Zeit (UTC+4)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      DB_JOURNAL: ${{ secrets.DB_JOURNAL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          set -e
          python -m pip install --upgrade pip
          pip install openai requests python-dotenv notion-client

      - name: Run GPT journal summary
        run: python gpt_journal_summary.py
