name: Journal Entry Creator

on:
  schedule:
    - cron: '0 23 * * *'  # 05:00 Dubai-Zeit (UTC+4)
  workflow_dispatch:

jobs:
  run-journal:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai requests python-dotenv

    - name: Run journal script
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        DB_TASKS: ${{ secrets.DB_TASKS }}
        DB_JOURNAL: ${{ secrets.DB_JOURNAL }}
        DB_NOTIZEN: ${{ secrets.DB_NOTIZEN }}
      run: python journal_creator.py
